name: pyhc
channels:
  - conda-forge
dependencies:
  - astropy=5.0.4
  - bokeh=2.4.3
  - cartopy=0.20.3
  - gfortran=11.2  # needed for ffnet dependency of spacepy
  - jupyter-book=0.12.3
  - jupyterlab=3.5.0
  - jupyterlab-git=0.39.3
  - matplotlib=3.5.3
  - netcdf4=1.5.8
  - numpy=1.23.4
  - pandas=1.3.5
  - pip
  - plasmapy=0.7.0
  - pre-commit
  - python=3.10
  - scipy=1.8.1
  - sunpy=3.1.8
  - watermark=2.3.1
  - xarray=0.20.2
  - pip:
    - aiapy==0.6.4
    - cdflib==0.3.20
    - hapiclient==0.2.5
    - hapiplot==0.2.1
    # - kamodo==21.10.*
    # - pysat==3.0.*
    - pyspedas==1.2.10
    - pytplot-mpl-temp==2.0.2
    - spacepy==0.2.3
