name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  pre-commit:
    name: Format (pre-commit)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: --hook-stage manual --all-files
  build-book:
    needs: pre-commit
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      # Setup conda environment
      - uses: actions/checkout@v3
      - name: Provision conda env
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          activate-environment: pyhc
          environment-file: environment/pyhc-gallery-fixed-conda.txt
      - name: Add pip packages
        run: |
          pip install -r environment/pyhc-gallery-fixed-pip.txt
      - name:  Display environment
        run: |
          conda info
          conda list
      # Build Jupyter Book site
      - name: Run jupyter-book build
        run: |
          jupyter-book build .
      # Deploy online preview
      - name: Deploy to Netlify
        if: always()
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './_build/html'
          production-deploy: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          github-deployment-environment: netlify-deploy
          github-deployment-description: "jbook preview on netlify"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      # Experimental steps that could be run before jupyter-book
      # Layer in pytest & nbmake (could be fragile)
      - name: Install nbmake
        run: |
          pip install pytest pytest-xdist nbmake
      # Execute notebooks with nbmake
      - name: Execute notebooks with nbmake
        run: |
          pytest --numprocesses 2 --nbmake --overwrite src/*.ipynb
